# Generated by cucumber-sinatra. (2013-09-27 10:53:05 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'
require 'database_cleaner/cucumber'
require_relative '../helpers/session'


Capybara.app = Chitter

DatabaseCleaner.strategy = :truncation

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
  include SessionHelpers
end

Before do
	DatabaseCleaner.start
end

Before('@sign_in_out') do 
	User.create(:name => 'Bob McBob',
  				:username => 'bobbo',
  				:email => 'bob@bobbo.com', 
              	:password => 'orange')
end

World do
  ChitterWorld.new
end

After do |scenario|
	DatabaseCleaner.clean
end
